services:
  user-service:
    build: ./User-Service
    ports:
      - "5001:5001"
    networks:
      - connectify-net
    depends_on:
      - mongo
      - redis

  admin-service:
    build: ./Admin-Service
    ports:
      - "5002:5002"
    networks:
      - connectify-net
    depends_on:
      - mongo

  auth-service:
    build: ./Auth-Service
    ports:
      - "5003:5003"
    networks:
      - connectify-net
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - connectify-net

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - connectify-net

networks:
  connectify-net:
    driver: bridge
